# Welcome to Jekyll!
# This config file is meant for settings that affect your entire site, values which you are expected to set up once and rarely need to edit after that. For technical reasons, this file is *NOT* reloaded automatically when you use `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
title                    : "Hello. I'm Marek Michalowski."
title_separator          : "-"
subtitle                 : # site tagline that appears below site title in masthead
name                     : "Marek Michalowski"
description              : "The personal web site of Marek Michalowski."
url                      : "https://marek.michalow.ski"
baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : "michalowski/michalowski.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : # path of logo image to display in the masthead, e.g. "/assets/images/88x88.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
copyright                : "Marek Michalowski"

remote_theme             : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
markdown                 : kramdown
locale                   : "en-US"
timezone                 : America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
permalink                : /:categories/:title/
paginate                 : 5 # amount of posts to show
paginate_path            : /page:num/
search                   : false

analytics:
  provider               : "google-gtag" # "google", "google-universal", "custom"
  google:
    tracking_id          : "G-2Q3WLEBJXN"
    anonymize_ip         : # true, false (default)

include:
  - _pages

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name                   : "Marek Michalowski"
  avatar                 : "/assets/logos/estop.svg"
  bio                    : "Co-founder of [Intrinsic](http://intrinsic.ai), [BeatBots](http://beatbots.net), [Dirty Robot](http://dirtyro.bot), & the [Robot Film Festival](http://robot.film)."
  location               : "San Francisco"
  email                  : 
  links:
    # - label: "Email"
      # icon: "fas fa-fw fa-envelope-square"
      # url: "mailto:your.name@email.com"
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "http://marek.michalow.ski"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "http://linkedin.com/in/mmichalowski"
    - label: "Github"
      icon: "fab fa-fw fa-github"
      url: "http://github.com/michalowski"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "http://instagram.com/mmichalowski"
    - label: "Bluesky"
      icon: "fab fa-fw fa-bluesky"
      url: "http://bsky.app/profile/michalow.ski"
    - label: "Mastodon"
      icon: "fab fa-fw fa-mastodon"
      url: "http://mastodon.social/@michalowski"
    - label: "Medium"
      icon: "fab fa-fw fa-medium"
      url: "http://medium.com/@mmichalowski"
    - label: "Scholar"
      icon: "fab fa-fw fa-google-scholar"
      url: "http://scholar.google.com/citations?user=y7S4e2gAAAAJ"

footer:
  links:
    - label: ""
      icon: "fab fa-fw fa-linkedin"
      url: "http://linkedin.com/in/mmichalowski"
    - label: ""
      icon: "fab fa-fw fa-github"
      url: "http://github.com/michalowski"
    - label: ""
      icon: "fab fa-fw fa-instagram"
      url: "http://instagram.com/mmichalowski"
    - label: ""
      icon: "fab fa-fw fa-bluesky"
      url: "http://bsky.app/profile/michalow.ski"
    - label: ""
      icon: "fab fa-fw fa-mastodon"
      url: "http://mastodon.social/@michalowski"
    - label: ""
      icon: "fab fa-fw fa-medium"
      url: "http://medium.com/@mmichalowski"
    - label: ""
      icon: "fab fa-fw fa-google-scholar"
      url: "http://scholar.google.com/citations?user=y7S4e2gAAAAJ"

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path

defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
